// ==============================================================================
// CMU Pronouncing Dictionary (CMUdict) Core Lexicon
// Provides standardized ARPAbet phoneme breakdowns for English vocabulary
// ==============================================================================

export const CMU_DICT: Record<string, string[]> = {
  // Common Everyday & Core Educational Words
  bat: ['B', 'AE1', 'T'],
  cat: ['K', 'AE1', 'T'],
  hat: ['HH', 'AE1', 'T'],
  rat: ['R', 'AE1', 'T'],
  mat: ['M', 'AE1', 'T'],
  fat: ['F', 'AE1', 'T'],
  map: ['M', 'AE1', 'P'],
  cap: ['K', 'AE1', 'P'],
  tap: ['T', 'AE1', 'P'],
  bag: ['B', 'AE1', 'G'],
  tag: ['T', 'AE1', 'G'],
  pen: ['P', 'EH1', 'N'],
  hen: ['HH', 'EH1', 'N'],
  ten: ['T', 'EH1', 'N'],
  bed: ['B', 'EH1', 'D'],
  red: ['R', 'EH1', 'D'],
  pet: ['P', 'EH1', 'T'],
  net: ['N', 'EH1', 'T'],
  leg: ['L', 'EH1', 'G'],
  pin: ['P', 'IH1', 'N'],
  bin: ['B', 'IH1', 'N'],
  win: ['W', 'IH1', 'N'],
  sit: ['S', 'IH1', 'T'],
  hit: ['HH', 'IH1', 'T'],
  fit: ['F', 'IH1', 'T'],
  pig: ['P', 'IH1', 'G'],
  big: ['B', 'IH1', 'G'],
  dig: ['D', 'IH1', 'G'],
  dog: ['D', 'AO1', 'G'],
  fog: ['F', 'AO1', 'G'],
  log: ['L', 'AO1', 'G'],
  hot: ['HH', 'AA1', 'T'],
  pot: ['P', 'AA1', 'T'],
  box: ['B', 'AA1', 'K', 'S'],
  fox: ['F', 'AA1', 'K', 'S'],
  bus: ['B', 'AH1', 'S'],
  cup: ['K', 'AH1', 'P'],
  sun: ['S', 'AH1', 'N'],
  run: ['R', 'AH1', 'N'],
  fun: ['F', 'AH1', 'N'],
  gun: ['G', 'AH1', 'N'],
  nut: ['N', 'AH1', 'T'],
  cut: ['K', 'AH1', 'T'],
  hut: ['HH', 'AH1', 'T'],
  bug: ['B', 'AH1', 'G'],
  hug: ['HH', 'AH1', 'G'],
  mug: ['M', 'AH1', 'G'],

  // Academic, Business & Modern Tech Words
  premium: ['P', 'R', 'IY1', 'M', 'IY0', 'AH0', 'M'],
  reading: ['R', 'IY1', 'D', 'IH0', 'NG'],
  read: ['R', 'IY1', 'D'],
  play: ['P', 'L', 'EY1'],
  playing: ['P', 'L', 'EY1', 'IH0', 'NG'],
  player: ['P', 'L', 'EY1', 'ER0'],
  leader: ['L', 'IY1', 'D', 'ER0'],
  leadership: ['L', 'IY1', 'D', 'ER0', 'SH', 'IH2', 'P'],
  lead: ['L', 'IY1', 'D'],
  schedule: ['S', 'K', 'EH1', 'JH', 'UW0', 'L'],
  education: ['EH2', 'JH', 'AH0', 'K', 'EY1', 'SH', 'AH0', 'N'],
  battery: ['B', 'AE1', 'T', 'ER0', 'IY0'],
  computer: ['K', 'AH0', 'M', 'P', 'Y', 'UW1', 'T', 'ER0'],
  digital: ['D', 'IH1', 'JH', 'AH0', 'T', 'AH0', 'L'],
  internet: ['IH1', 'N', 'T', 'ER0', 'N', 'EH2', 'T'],
  network: ['N', 'EH1', 'T', 'W', 'ER2', 'K'],
  topology: ['T', 'OW0', 'P', 'AA1', 'L', 'AH0', 'JH', 'IY0'],
  algorithm: ['AE1', 'L', 'G', 'ER0', 'IH2', 'DH', 'AH0', 'M'],
  database: ['D', 'EY1', 'T', 'AH0', 'B', 'EY2', 'S'],
  server: ['S', 'ER1', 'V', 'ER0'],
  program: ['P', 'R', 'OW1', 'G', 'R', 'AE2', 'M'],
  system: ['S', 'IH1', 'S', 'T', 'AH0', 'M'],
  science: ['S', 'AY1', 'AH0', 'N', 'S'],
  technology: ['T', 'EH0', 'K', 'N', 'AA1', 'L', 'AH0', 'JH', 'IY0'],
  information: ['IH2', 'N', 'F', 'ER0', 'M', 'EY1', 'SH', 'AH0', 'N'],
  communication: ['K', 'AH0', 'M', 'Y', 'UW2', 'N', 'AH0', 'K', 'EY1', 'SH', 'AH0', 'N'],
  development: ['D', 'IH0', 'V', 'EH1', 'L', 'AH0', 'P', 'M', 'AH0', 'N', 'T'],
  management: ['M', 'AE1', 'N', 'AH0', 'JH', 'M', 'AH0', 'N', 'T'],
  project: ['P', 'R', 'AA1', 'JH', 'EH0', 'K', 'T'],
  strategy: ['S', 'T', 'R', 'AE1', 'T', 'AH0', 'JH', 'IY0'],
  process: ['P', 'R', 'AA1', 'S', 'EH2', 'S'],
  product: ['P', 'R', 'AA1', 'D', 'AH0', 'K', 'T'],
  service: ['S', 'ER1', 'V', 'AH0', 'S'],
  market: ['M', 'AA1', 'R', 'K', 'AH0', 'T'],
  marketing: ['M', 'AA1', 'R', 'K', 'AH0', 'T', 'IH0', 'NG'],
  business: ['B', 'IH1', 'Z', 'N', 'AH0', 'S'],
  company: ['K', 'AH1', 'M', 'P', 'AH0', 'N', 'IY0'],
  industry: ['IH1', 'N', 'D', 'AH0', 'S', 'T', 'R', 'IY0'],
  economy: ['IH0', 'K', 'AA1', 'N', 'AH0', 'M', 'IY0'],
  finance: ['F', 'AH0', 'N', 'AE1', 'N', 'S'],
  financial: ['F', 'AH0', 'N', 'AE1', 'N', 'SH', 'AH0', 'L'],
  investment: ['IH0', 'N', 'V', 'EH1', 'S', 'T', 'M', 'AH0', 'N', 'T'],
  customer: ['K', 'AH1', 'S', 'T', 'AH0', 'M', 'ER0'],
  consumer: ['K', 'AH0', 'N', 'S', 'UW1', 'M', 'ER0'],
  community: ['K', 'AH0', 'M', 'Y', 'UW1', 'N', 'AH0', 'T', 'IY0'],
  society: ['S', 'AH0', 'S', 'AY1', 'AH0', 'T', 'IY0'],
  culture: ['K', 'AH1', 'L', 'CH', 'ER0'],
  history: ['HH', 'IH1', 'S', 'T', 'ER0', 'IY0'],
  language: ['L', 'AE1', 'NG', 'G', 'W', 'AH0', 'JH'],
  vocabulary: ['V', 'OW0', 'K', 'AE1', 'B', 'Y', 'AH0', 'L', 'EH2', 'R', 'IY0'],
  grammar: ['G', 'R', 'AE1', 'M', 'ER0'],
  sentence: ['S', 'EH1', 'N', 'T', 'AH0', 'N', 'S'],
  paragraph: ['P', 'AE1', 'R', 'AH0', 'G', 'R', 'AE2', 'F'],
  article: ['AA1', 'R', 'T', 'AH0', 'K', 'AH0', 'L'],
  chapter: ['CH', 'AE1', 'P', 'T', 'ER0'],
  lesson: ['L', 'EH1', 'S', 'AH0', 'N'],
  exercise: ['EH1', 'K', 'S', 'ER0', 'S', 'AY2', 'Z'],
  practice: ['P', 'R', 'AE1', 'K', 'T', 'AH0', 'S'],
  activity: ['AE0', 'K', 'T', 'IH1', 'V', 'AH0', 'T', 'IY0'],
  game: ['G', 'EY1', 'M'],
  flashcard: ['F', 'L', 'AE1', 'SH', 'K', 'AA2', 'R', 'D'],
  quiz: ['K', 'W', 'IH1', 'Z'],
  test: ['T', 'EH1', 'S', 'T'],
  exam: ['IH0', 'G', 'Z', 'AE1', 'M'],
  grade: ['G', 'R', 'EY1', 'D'],
  score: ['S', 'K', 'AO1', 'R'],
  result: ['R', 'IH0', 'Z', 'AH1', 'L', 'T'],
  level: ['L', 'EH1', 'V', 'AH0', 'L'],
  mastery: ['M', 'AE1', 'S', 'T', 'ER0', 'IY0'],
  progress: ['P', 'R', 'AA1', 'G', 'R', 'EH2', 'S'],
  growth: ['G', 'R', 'OW1', 'TH'],
  success: ['S', 'AH0', 'K', 'S', 'EH1', 'S'],
  achievement: ['AH0', 'CH', 'IY1', 'V', 'M', 'AH0', 'N', 'T'],
  challenge: ['CH', 'AE1', 'L', 'AH0', 'N', 'JH'],
  opportunity: ['AA2', 'P', 'ER0', 'T', 'UW1', 'N', 'AH0', 'T', 'IY0'],
  experience: ['IH0', 'K', 'S', 'P', 'IH1', 'R', 'IY0', 'AH0', 'N', 'S'],
  knowledge: ['N', 'AA1', 'L', 'AH0', 'JH'],
  skill: ['S', 'K', 'IH1', 'L'],
  ability: ['AH0', 'B', 'IH1', 'L', 'AH0', 'T', 'IY0'],
  talent: ['T', 'AE1', 'L', 'AH0', 'N', 'T'],
  potential: ['P', 'AH0', 'T', 'EH1', 'N', 'SH', 'AH0', 'L'],
  future: ['F', 'Y', 'UW1', 'CH', 'ER0'],
  dream: ['D', 'R', 'IY1', 'M'],
  goal: ['G', 'OW1', 'L'],
  purpose: ['P', 'ER1', 'P', 'AH0', 'S'],
  passion: ['P', 'AE1', 'SH', 'AH0', 'N'],
  energy: ['EH1', 'N', 'ER0', 'JH', 'IY0'],
  power: ['P', 'AW1', 'ER0'],
  strength: ['S', 'T', 'R', 'EH1', 'NG', 'K', 'TH'],
  health: ['HH', 'EH1', 'L', 'TH'],
  nature: ['N', 'EY1', 'CH', 'ER0'],
  environment: ['IH0', 'N', 'V', 'AY1', 'R', 'AH0', 'N', 'M', 'AH0', 'N', 'T'],
  planet: ['P', 'L', 'AE1', 'N', 'AH0', 'T'],
  world: ['W', 'ER1', 'L', 'D'],
  universe: ['Y', 'UW1', 'N', 'AH0', 'V', 'ER2', 'S'],

  // Character Traits & Educational Core
  resilience: ['R', 'IH0', 'Z', 'IH1', 'L', 'Y', 'AH0', 'N', 'S'],
  diligent: ['D', 'IH1', 'L', 'AH0', 'JH', 'AH0', 'N', 'T'],
  courage: ['K', 'ER1', 'AH0', 'JH'],
  courageous: ['K', 'ER0', 'EY1', 'JH', 'AH0', 'S'],
  explore: ['IH0', 'K', 'S', 'P', 'L', 'AO1', 'R'],
  achieve: ['AH0', 'CH', 'IY1', 'V'],
  curious: ['K', 'Y', 'UH1', 'R', 'IY0', 'AH0', 'S'],
  brilliant: ['B', 'R', 'IH1', 'L', 'Y', 'AH0', 'N', 'T'],
  creativity: ['K', 'R', 'IY0', 'EY0', 'T', 'IH1', 'V', 'AH0', 'T', 'IY0'],
  enthusiasm: ['IH0', 'N', 'TH', 'UW1', 'Z', 'IY0', 'AE2', 'Z', 'AH0', 'M'],
  persevere: ['P', 'ER2', 'S', 'AH0', 'V', 'IH1', 'R'],
  magnificent: ['M', 'AE0', 'G', 'N', 'IH1', 'F', 'AH0', 'S', 'AH0', 'N', 'T'],
  innovation: ['IH2', 'N', 'AH0', 'V', 'EY1', 'SH', 'AH0', 'N'],
};
