name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_RIVER_0A45EC400 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist"
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}${{ vars.VITE_SUPABASE_ANON_KEY }}
          VITE_AZURE_TRANSLATOR_KEY: ${{ secrets.VITE_AZURE_TRANSLATOR_KEY }}${{ vars.VITE_AZURE_TRANSLATOR_KEY }}
          VITE_AZURE_TRANSLATOR_REGION: ${{ secrets.VITE_AZURE_TRANSLATOR_REGION }}${{ vars.VITE_AZURE_TRANSLATOR_REGION }}
          VITE_AZURE_SPEECH_KEY: ${{ secrets.VITE_AZURE_SPEECH_KEY }}${{ vars.VITE_AZURE_SPEECH_KEY }}
          VITE_AZURE_SPEECH_REGION: ${{ secrets.VITE_AZURE_SPEECH_REGION }}${{ vars.VITE_AZURE_SPEECH_REGION }}
          VITE_AZURE_OPENAI_ENDPOINT: ${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}${{ vars.VITE_AZURE_OPENAI_ENDPOINT }}
          VITE_AZURE_OPENAI_KEY: ${{ secrets.VITE_AZURE_OPENAI_KEY }}${{ vars.VITE_AZURE_OPENAI_KEY }}
          VITE_AZURE_OPENAI_DEPLOYMENT: ${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}${{ vars.VITE_AZURE_OPENAI_DEPLOYMENT }}
          VITE_AZURE_OPENAI_API_VERSION: ${{ secrets.VITE_AZURE_OPENAI_API_VERSION }}${{ vars.VITE_AZURE_OPENAI_API_VERSION }}
          VITE_OCR_SPACE_API_KEY: ${{ secrets.VITE_OCR_SPACE_API_KEY }}${{ vars.VITE_OCR_SPACE_API_KEY }}
          VITE_LIFF_ID: ${{ secrets.VITE_LIFF_ID }}${{ vars.VITE_LIFF_ID }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_RIVER_0A45EC400 }}
          action: "close"
